---
apiVersion: v1
kind: Service
metadata:
  name: k8sprobetester
  namespace: default
spec:
  selector:
    app: k8sprobetester
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80